export declare const GLOB_SRC_EXT = "{js,cjs,mjs,jsx,ts,cts,mts,tsx}";
export declare const GLOB_SRC = "**/*.{js,cjs,mjs,jsx,ts,cts,mts,tsx}";
export declare const GLOB_JS = "**/*.{js,cjs,mjs}";
export declare const GLOB_JSX = "**/*.jsx";
export declare const GLOB_TS = "**/*.{ts,cts,mts}";
export declare const GLOB_TSX = "**/*.tsx";
export declare const GLOB_DTS = "**/*.d.{ts,cts,mts}";
export declare const GLOB_VUE = "**/*.vue";
export declare const GLOB_TESTS: string[];
export declare const GLOB_EXCLUDE: string[];
