import { GLOB_JS, GLOB_TS, GLOB_DTS, GLOB_JSX, GLOB_TSX } from './constants.js'

export const plugins = ['typescript']

export const rules = {
    'typescript/consistent-type-definitions': ['error', 'type'],
    'typescript/dot-notation': ['error', { allowKeywords: true }],
}

const TYPE_AWARE_OFF = {
    'typescript/await-thenable': 'off',
    'typescript/consistent-return': 'off',
    'typescript/consistent-type-exports': 'off',
    'typescript/dot-notation': 'off',
    'typescript/no-array-delete': 'off',
    'typescript/no-base-to-string': 'off',
    'typescript/no-confusing-void-expression': 'off',
    'typescript/no-deprecated': 'off',
    'typescript/no-duplicate-type-constituents': 'off',
    'typescript/no-floating-promises': 'off',
    'typescript/no-for-in-array': 'off',
    'typescript/no-implied-eval': 'off',
    'typescript/no-meaningless-void-operator': 'off',
    'typescript/no-misused-promises': 'off',
    'typescript/no-misused-spread': 'off',
    'typescript/no-mixed-enums': 'off',
    'typescript/no-redundant-type-constituents': 'off',
    'typescript/no-unnecessary-qualifier': 'off',
    'typescript/no-unnecessary-template-expression': 'off',
    'typescript/no-unnecessary-type-arguments': 'off',
    'typescript/no-unnecessary-type-assertion': 'off',
    'typescript/no-unnecessary-type-conversion': 'off',
    'typescript/no-unnecessary-type-parameters': 'off',
    'typescript/no-unsafe-argument': 'off',
    'typescript/no-unsafe-assignment': 'off',
    'typescript/no-unsafe-call': 'off',
    'typescript/no-unsafe-enum-comparison': 'off',
    'typescript/no-unsafe-member-access': 'off',
    'typescript/no-unsafe-return': 'off',
    'typescript/no-unsafe-type-assertion': 'off',
    'typescript/no-unsafe-unary-minus': 'off',
    'typescript/no-useless-default-assignment': 'off',
    'typescript/non-nullable-type-assertion-style': 'off',
    'typescript/only-throw-error': 'off',
    'typescript/prefer-find': 'off',
    'typescript/prefer-includes': 'off',
    'typescript/prefer-nullish-coalescing': 'off',
    'typescript/prefer-promise-reject-errors': 'off',
    'typescript/prefer-readonly': 'off',
    'typescript/prefer-reduce-type-parameter': 'off',
    'typescript/prefer-regexp-exec': 'off',
    'typescript/prefer-return-this-type': 'off',
    'typescript/prefer-string-starts-ends-with': 'off',
    'typescript/promise-function-async': 'off',
    'typescript/related-getter-setter-pairs': 'off',
    'typescript/require-array-sort-compare': 'off',
    'typescript/require-await': 'off',
    'typescript/restrict-plus-operands': 'off',
    'typescript/return-await': 'off',
    'typescript/strict-boolean-expressions': 'off',
    'typescript/strict-void-return': 'off',
    'typescript/switch-exhaustiveness-check': 'off',
    'typescript/unbound-method': 'off',
    'typescript/use-unknown-in-catch-callback-variable': 'off',
}

export const overrides = [
    {
        files: [GLOB_TS, GLOB_TSX],
        rules: {
            'no-implied-eval': 'off',
            'no-throw-literal': 'off',
            'no-unused-expressions': [
                'error',
                { allowShortCircuit: true, allowTernary: true, enforceForJSX: true },
            ],
            'require-await': 'off',
            'typescript/await-thenable': 'error',
            'typescript/ban-ts-comment': ['error', { 'ts-ignore': 'allow-with-description' }],
            'typescript/ban-tslint-comment': 'error',
            'typescript/consistent-type-imports': [
                'error',
                { disallowTypeAnnotations: false, prefer: 'type-imports' },
            ],
            'typescript/no-base-to-string': 'error',
            'typescript/no-confusing-void-expression': 'error',
            'typescript/no-dynamic-delete': 'error',
            'typescript/no-extraneous-class': 'error',
            'typescript/no-floating-promises': 'error',
            'typescript/no-for-in-array': 'error',
            'typescript/no-implied-eval': 'error',
            'typescript/no-import-type-side-effects': 'error',
            'typescript/no-misused-new': 'error',
            'typescript/no-misused-promises': 'error',
            'typescript/no-this-alias': 'error',
            'typescript/no-unnecessary-type-assertion': 'error',
            'typescript/only-throw-error': 'error',
            'typescript/prefer-for-of': 'error',
            'typescript/prefer-includes': 'error',
            'typescript/prefer-optional-chain': 'error',
            'typescript/prefer-string-starts-ends-with': 'error',
            'typescript/promise-function-async': 'error',
            'typescript/require-array-sort-compare': 'error',
            'typescript/require-await': 'error',
            'typescript/return-await': ['error', 'in-try-catch'],
            'typescript/unbound-method': 'error',
        },
    },
    {
        files: [GLOB_JS, GLOB_JSX, GLOB_DTS],
        rules: TYPE_AWARE_OFF,
    },
    {
        files: [GLOB_DTS],
        rules: {
            'import/no-duplicates': 'off',
            'no-unused-vars': 'off',
        },
    },
]

export default { overrides, plugins, rules }
