export declare const plugins: string[];
export declare const rules: {
    'typescript/consistent-type-definitions': string[];
    'typescript/dot-notation': (string | {
        allowKeywords: boolean;
    })[];
};
export declare const overrides: ({
    files: string[];
    rules: {
        'no-implied-eval': string;
        'no-throw-literal': string;
        'no-unused-expressions': (string | {
            allowShortCircuit: boolean;
            allowTernary: boolean;
            enforceForJSX: boolean;
        })[];
        'require-await': string;
        'typescript/await-thenable': string;
        'typescript/ban-ts-comment': (string | {
            'ts-ignore': string;
        })[];
        'typescript/ban-tslint-comment': string;
        'typescript/consistent-type-imports': (string | {
            disallowTypeAnnotations: boolean;
            prefer: string;
        })[];
        'typescript/no-base-to-string': string;
        'typescript/no-confusing-void-expression': string;
        'typescript/no-dynamic-delete': string;
        'typescript/no-extraneous-class': string;
        'typescript/no-floating-promises': string;
        'typescript/no-for-in-array': string;
        'typescript/no-implied-eval': string;
        'typescript/no-import-type-side-effects': string;
        'typescript/no-misused-new': string;
        'typescript/no-misused-promises': string;
        'typescript/no-this-alias': string;
        'typescript/no-unnecessary-type-assertion': string;
        'typescript/only-throw-error': string;
        'typescript/prefer-for-of': string;
        'typescript/prefer-includes': string;
        'typescript/prefer-optional-chain': string;
        'typescript/prefer-string-starts-ends-with': string;
        'typescript/promise-function-async': string;
        'typescript/require-array-sort-compare': string;
        'typescript/require-await': string;
        'typescript/return-await': string[];
        'typescript/unbound-method': string;
        'import/no-duplicates'?: undefined;
        'no-unused-vars'?: undefined;
    };
} | {
    files: string[];
    rules: {
        'typescript/await-thenable': string;
        'typescript/consistent-return': string;
        'typescript/consistent-type-exports': string;
        'typescript/dot-notation': string;
        'typescript/no-array-delete': string;
        'typescript/no-base-to-string': string;
        'typescript/no-confusing-void-expression': string;
        'typescript/no-deprecated': string;
        'typescript/no-duplicate-type-constituents': string;
        'typescript/no-floating-promises': string;
        'typescript/no-for-in-array': string;
        'typescript/no-implied-eval': string;
        'typescript/no-meaningless-void-operator': string;
        'typescript/no-misused-promises': string;
        'typescript/no-misused-spread': string;
        'typescript/no-mixed-enums': string;
        'typescript/no-redundant-type-constituents': string;
        'typescript/no-unnecessary-qualifier': string;
        'typescript/no-unnecessary-template-expression': string;
        'typescript/no-unnecessary-type-arguments': string;
        'typescript/no-unnecessary-type-assertion': string;
        'typescript/no-unnecessary-type-conversion': string;
        'typescript/no-unnecessary-type-parameters': string;
        'typescript/no-unsafe-argument': string;
        'typescript/no-unsafe-assignment': string;
        'typescript/no-unsafe-call': string;
        'typescript/no-unsafe-enum-comparison': string;
        'typescript/no-unsafe-member-access': string;
        'typescript/no-unsafe-return': string;
        'typescript/no-unsafe-type-assertion': string;
        'typescript/no-unsafe-unary-minus': string;
        'typescript/no-useless-default-assignment': string;
        'typescript/non-nullable-type-assertion-style': string;
        'typescript/only-throw-error': string;
        'typescript/prefer-find': string;
        'typescript/prefer-includes': string;
        'typescript/prefer-nullish-coalescing': string;
        'typescript/prefer-promise-reject-errors': string;
        'typescript/prefer-readonly': string;
        'typescript/prefer-reduce-type-parameter': string;
        'typescript/prefer-regexp-exec': string;
        'typescript/prefer-return-this-type': string;
        'typescript/prefer-string-starts-ends-with': string;
        'typescript/promise-function-async': string;
        'typescript/related-getter-setter-pairs': string;
        'typescript/require-array-sort-compare': string;
        'typescript/require-await': string;
        'typescript/restrict-plus-operands': string;
        'typescript/return-await': string;
        'typescript/strict-boolean-expressions': string;
        'typescript/strict-void-return': string;
        'typescript/switch-exhaustiveness-check': string;
        'typescript/unbound-method': string;
        'typescript/use-unknown-in-catch-callback-variable': string;
    };
} | {
    files: string[];
    rules: {
        'no-implied-eval'?: undefined;
        'no-throw-literal'?: undefined;
        'no-unused-expressions'?: undefined;
        'require-await'?: undefined;
        'typescript/await-thenable'?: undefined;
        'typescript/ban-ts-comment'?: undefined;
        'typescript/ban-tslint-comment'?: undefined;
        'typescript/consistent-type-imports'?: undefined;
        'typescript/no-base-to-string'?: undefined;
        'typescript/no-confusing-void-expression'?: undefined;
        'typescript/no-dynamic-delete'?: undefined;
        'typescript/no-extraneous-class'?: undefined;
        'typescript/no-floating-promises'?: undefined;
        'typescript/no-for-in-array'?: undefined;
        'typescript/no-implied-eval'?: undefined;
        'typescript/no-import-type-side-effects'?: undefined;
        'typescript/no-misused-new'?: undefined;
        'typescript/no-misused-promises'?: undefined;
        'typescript/no-this-alias'?: undefined;
        'typescript/no-unnecessary-type-assertion'?: undefined;
        'typescript/only-throw-error'?: undefined;
        'typescript/prefer-for-of'?: undefined;
        'typescript/prefer-includes'?: undefined;
        'typescript/prefer-optional-chain'?: undefined;
        'typescript/prefer-string-starts-ends-with'?: undefined;
        'typescript/promise-function-async'?: undefined;
        'typescript/require-array-sort-compare'?: undefined;
        'typescript/require-await'?: undefined;
        'typescript/return-await'?: undefined;
        'typescript/unbound-method'?: undefined;
        'import/no-duplicates': string;
        'no-unused-vars': string;
    };
})[];
declare const _default: {
    overrides: ({
        files: string[];
        rules: {
            'no-implied-eval': string;
            'no-throw-literal': string;
            'no-unused-expressions': (string | {
                allowShortCircuit: boolean;
                allowTernary: boolean;
                enforceForJSX: boolean;
            })[];
            'require-await': string;
            'typescript/await-thenable': string;
            'typescript/ban-ts-comment': (string | {
                'ts-ignore': string;
            })[];
            'typescript/ban-tslint-comment': string;
            'typescript/consistent-type-imports': (string | {
                disallowTypeAnnotations: boolean;
                prefer: string;
            })[];
            'typescript/no-base-to-string': string;
            'typescript/no-confusing-void-expression': string;
            'typescript/no-dynamic-delete': string;
            'typescript/no-extraneous-class': string;
            'typescript/no-floating-promises': string;
            'typescript/no-for-in-array': string;
            'typescript/no-implied-eval': string;
            'typescript/no-import-type-side-effects': string;
            'typescript/no-misused-new': string;
            'typescript/no-misused-promises': string;
            'typescript/no-this-alias': string;
            'typescript/no-unnecessary-type-assertion': string;
            'typescript/only-throw-error': string;
            'typescript/prefer-for-of': string;
            'typescript/prefer-includes': string;
            'typescript/prefer-optional-chain': string;
            'typescript/prefer-string-starts-ends-with': string;
            'typescript/promise-function-async': string;
            'typescript/require-array-sort-compare': string;
            'typescript/require-await': string;
            'typescript/return-await': string[];
            'typescript/unbound-method': string;
            'import/no-duplicates'?: undefined;
            'no-unused-vars'?: undefined;
        };
    } | {
        files: string[];
        rules: {
            'typescript/await-thenable': string;
            'typescript/consistent-return': string;
            'typescript/consistent-type-exports': string;
            'typescript/dot-notation': string;
            'typescript/no-array-delete': string;
            'typescript/no-base-to-string': string;
            'typescript/no-confusing-void-expression': string;
            'typescript/no-deprecated': string;
            'typescript/no-duplicate-type-constituents': string;
            'typescript/no-floating-promises': string;
            'typescript/no-for-in-array': string;
            'typescript/no-implied-eval': string;
            'typescript/no-meaningless-void-operator': string;
            'typescript/no-misused-promises': string;
            'typescript/no-misused-spread': string;
            'typescript/no-mixed-enums': string;
            'typescript/no-redundant-type-constituents': string;
            'typescript/no-unnecessary-qualifier': string;
            'typescript/no-unnecessary-template-expression': string;
            'typescript/no-unnecessary-type-arguments': string;
            'typescript/no-unnecessary-type-assertion': string;
            'typescript/no-unnecessary-type-conversion': string;
            'typescript/no-unnecessary-type-parameters': string;
            'typescript/no-unsafe-argument': string;
            'typescript/no-unsafe-assignment': string;
            'typescript/no-unsafe-call': string;
            'typescript/no-unsafe-enum-comparison': string;
            'typescript/no-unsafe-member-access': string;
            'typescript/no-unsafe-return': string;
            'typescript/no-unsafe-type-assertion': string;
            'typescript/no-unsafe-unary-minus': string;
            'typescript/no-useless-default-assignment': string;
            'typescript/non-nullable-type-assertion-style': string;
            'typescript/only-throw-error': string;
            'typescript/prefer-find': string;
            'typescript/prefer-includes': string;
            'typescript/prefer-nullish-coalescing': string;
            'typescript/prefer-promise-reject-errors': string;
            'typescript/prefer-readonly': string;
            'typescript/prefer-reduce-type-parameter': string;
            'typescript/prefer-regexp-exec': string;
            'typescript/prefer-return-this-type': string;
            'typescript/prefer-string-starts-ends-with': string;
            'typescript/promise-function-async': string;
            'typescript/related-getter-setter-pairs': string;
            'typescript/require-array-sort-compare': string;
            'typescript/require-await': string;
            'typescript/restrict-plus-operands': string;
            'typescript/return-await': string;
            'typescript/strict-boolean-expressions': string;
            'typescript/strict-void-return': string;
            'typescript/switch-exhaustiveness-check': string;
            'typescript/unbound-method': string;
            'typescript/use-unknown-in-catch-callback-variable': string;
        };
    } | {
        files: string[];
        rules: {
            'no-implied-eval'?: undefined;
            'no-throw-literal'?: undefined;
            'no-unused-expressions'?: undefined;
            'require-await'?: undefined;
            'typescript/await-thenable'?: undefined;
            'typescript/ban-ts-comment'?: undefined;
            'typescript/ban-tslint-comment'?: undefined;
            'typescript/consistent-type-imports'?: undefined;
            'typescript/no-base-to-string'?: undefined;
            'typescript/no-confusing-void-expression'?: undefined;
            'typescript/no-dynamic-delete'?: undefined;
            'typescript/no-extraneous-class'?: undefined;
            'typescript/no-floating-promises'?: undefined;
            'typescript/no-for-in-array'?: undefined;
            'typescript/no-implied-eval'?: undefined;
            'typescript/no-import-type-side-effects'?: undefined;
            'typescript/no-misused-new'?: undefined;
            'typescript/no-misused-promises'?: undefined;
            'typescript/no-this-alias'?: undefined;
            'typescript/no-unnecessary-type-assertion'?: undefined;
            'typescript/only-throw-error'?: undefined;
            'typescript/prefer-for-of'?: undefined;
            'typescript/prefer-includes'?: undefined;
            'typescript/prefer-optional-chain'?: undefined;
            'typescript/prefer-string-starts-ends-with'?: undefined;
            'typescript/promise-function-async'?: undefined;
            'typescript/require-array-sort-compare'?: undefined;
            'typescript/require-await'?: undefined;
            'typescript/return-await'?: undefined;
            'typescript/unbound-method'?: undefined;
            'import/no-duplicates': string;
            'no-unused-vars': string;
        };
    })[];
    plugins: string[];
    rules: {
        'typescript/consistent-type-definitions': string[];
        'typescript/dot-notation': (string | {
            allowKeywords: boolean;
        })[];
    };
};
export default _default;
